### ISSUE TITLE
jwt malformed

### ISSUE THREAD

**Issue by AndrewFraserClickT** [Xray-App/xray-postman-collections#3]
With many responses, I recieve the following response 

{"error":"Invalid JWT: JsonWebTokenError: jwt malformed"}

any thoughts?
![image](https://user-images.githubusercontent.com/68813826/94935299-ccbd6f00-04c4-11eb-81a4-dd2c153f13d7.png)

Authentication & get Xray custom fields work as expected

**Comment by bitcoder** [comment]
Hi,

1. have you defined these variables in the environment you're using, as detailed in the documentation??

client_id
client_secret
JIRA_BASEURL
JIRA_USERNAME
JIRA_PASSWORD

2. If so, what was the result of the "authentication" request you have inside the REST API folder?

3. Can you please check the "AUTH_TOKEN" variable value?

**Comment by bitcoder** [comment]
closing due to lack of feedback
