### ISSUE TITLE
Link to  Cloud collection in the README is broken

### ISSUE THREAD

**Issue by i-ivd** [Xray-App/xray-postman-collections#9]
The Link mentioned in the Readme file for the Cloud  collection is incorrect.

Link mentioned is for file `Xray Cloud GraphQLAPI.postman_collection `

The correct file name is  ` Xray_Cloud_GraphQL_API.postman_collection.json`

**Comment by bitcoder** [comment]
thanks for reporting @i-ivd . fixed
